spring.application.name=unit-2-final-project
spring.datasource.url=jdbc:mysql://localhost:3306/springboot2?useSSL=false
spring.datasource.username=root
spring.datasource.password=launchcode26
spring.jpa.hibernate.ddl-auto=update
